language: php
php:
  # - '5.4'
  - '5.5'
  - '5.6'
  - '7.0'
  # - hhvm
  # - nightly

services:
  - mysql

before_script: 
  - composer install
  - mysql -e "create database base_api_test_db;"
  - mysql -u root -e "CREATE USER 'homestead'@'localhost' IDENTIFIED BY 'secret'; GRANT ALL PRIVILEGES ON * . * TO 'homestead'@'localhost'; FLUSH PRIVILEGES;"
  - php artisan migrate --env=testing
  
script: ./vendor/bin/phpunit --coverage-clover clover.xml

after_success:
  - travis_retry ./vendor/bin/coveralls -v